### ISSUE TITLE
QuickSort 클래스를 굳이 인스턴스로 만들 필유가 있나?

### ISSUE THREAD

**Issue by o1o9814** [Hanyang-Tech-High-School/Algorithm#1]
static 클래스로 만들었으면 더 좋게 사용할 수 있었을 것 같음.

```java
public static class QuickSort {
    public static void sort() {
    }
}
```

use:
```java
QuickSort.sort();
```

**Comment by wcyoung** [comment]
public static class로 변경하니까 QuickSort에 빨간 밑줄 생기면서
Illegal modifier for the class QuickSort; only public, abstract & final are permitted
이런 오류가 나는데 많이 찾아보진 않았는데 왜인지 모르겠음 혹시 알고 있어?
